#!/usr/bin/env python3
""" Listing of source file declarations. """

import sys
import os

from postiats import declarations
from postiats import locations


def perror(message):
    """ Shorthand to print to `stderr`. """
    print(message, file=sys.stderr)


def error(message):
    """ `perror` and `sys.exit(1)`. """
    perror(message)
    sys.exit(1)


def print_loc(loc):
    """ Shorthand to parse and print formated loc. """
    loc = locations.parse(loc)
    loc = locations.ide_formated(loc)
    print(loc)


def dump():
    """ Dump declarations. """
    for value in declarations.DECLARATIONS:
        print("=========================")
        print(value.stamp.name)
        print(value.construct)
        if value.types:
            print("Type: %s" % ", ".join(value.types))
        if value.sorts:
            print("Sort: %s" % ", ".join(value.sorts))
        print_loc(value.loc)


def main():
    """ Main. """
    my_name = os.path.split(sys.argv[0])[1]

    recursive = False
    if len(sys.argv) >= 2 and sys.argv[1] == "-r":
        recursive = True
        del sys.argv[1]

    if len(sys.argv) != 2:
        error("Usage: %s [-r] file-name." % my_name)

    path = sys.argv[1]
    declarations.handle_source_file(path)
    dump()

    if recursive:
        done = set()
        while True:
            to_be_done = declarations.STALOADED.difference(done)
            done.update(declarations.STALOADED)
            declarations.STAMPS.clear()
            declarations.DECLARATIONS.clear()
            declarations.STALOADED.clear()
            if not to_be_done:
                break
            for path in to_be_done:
                declarations.handle_source_file(path)
                dump()


if __name__ == "__main__":
    main()
