#!/usr/bin/env python3
# -*- coding:utf-8; mode:python3; indent-tabs-mode:nil; tab-width:4; -*-

""" Wrapper script to invoke `postiats.jsonized.main()`. """

import postiats.jsonized

# ============================================================================

if __name__ == "__main__":
    postiats.jsonized.main()
