#!/usr/bin/env python3
# -*- coding:utf-8; mode:python3; indent-tabs-mode:nil; tab-width:4; -*-

""" Wrapper script to invoke `postiats.filter.main()`. """

import postiats.filter

# ============================================================================

if __name__ == "__main__":
    postiats.filter.main()
